### PR TITLE
fix(imageviewer): center image when only one image

### PR DESCRIPTION
**Pull request by Birkbjo**
This seems to have been introduced when upgrading to react@16. Updating react-slick and the styling seems to fix it. I can add the styling as static-assets instead of using the CDN - feedback welcome.

I've also lowered the padding so that the edge of the next-image is not shown anymore. Got some feedback that this looked like weird.

### CODE REVIEW

**Review by mediremi — APPROVED** [review]

**Comment by mediremi** [comment]
LGTM :ok_hand:

**Comment by amcgee** [comment]
I think it would be better not to use a CDN?  Does `react-slick` not include the dependency?

**Comment by amcgee** [comment]
I think it would be better not to use a CDN?  Does `react-slick` not include the dependency?

**Comment by mediremi** [comment]
> I think it would be better not to use a CDN

I'd rather not use a CDN either but I guess that should be a separate PR since it would require adding a build process for the stylsheets?

**Comment by Birkbjo** [comment]
I'm pretty sure webpack is configured so that we could just `import "slick-carousel/slick/slick.css";` in the entrypoint. 
Don't remember why it's using CDN for these, as they are very minimal.

**Comment by amcgee** [comment]
@Birkbjo great - yeah let's do that.  Another PR is probably reasonable for that change

**Comment by Birkbjo** [comment]
Cool, I've created a new PR for that here. Will merge next into this branch once that is merged to next.

**Pull request merged**
