### PR TITLE
fix: improve README instructions for local installation

### PR DESCRIPTION
**Pull request by mediremi**
To simplify local installation, I've moved some tasks (such as creating database tables and seeding them) to `package.json` scripts and have updated the README accordingly.

I've also moved the backend configuration documentation to `.env.template`.

### CODE REVIEW

**Review by amcgee — APPROVED** [review]
Looks good to me - @Birkbjo can you confirm?

**Review by Birkbjo — APPROVED** [review]
Nice, LGTM

**Comment by amcgee** [comment]
@mediremi for reference this should not have been a `fix` - it triggered an unnecessary production deploy and version bump (this should use `docs`)

**Comment by amcgee** [comment]
Also README changes probably don't need to go through `next`, but maybe worth it here since it's ahead of `master` @Birkbjo

**Pull request merged**
